name: Lighthouse CI

on:
  push:
    branches:
      - main
    paths:
      - 'landing-pages/**'
  pull_request:
    branches:
      - main
    paths:
      - 'landing-pages/**'

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          # Run Lighthouse CI using the config file
          lhci autorun

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const resultsPath = '.lighthouseci';
            
            if (fs.existsSync(resultsPath)) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '✅ Lighthouse CI analysis complete! Check the workflow logs for detailed results.'
              });
            }
